# Environment Settings
gpu: '0'                # Set CUDA_VISIBLE_DEVICES, default for cuda:0 only
device: 'cuda'          # Set running device
verbose: 20             # Logging Level, 0, 10, ..., 50; Default: 20 -> logging.info
log_file: ''            # Logging file path
model_path: ''          # The path to save model
random_seed: 3407       # Random seed of numpy and pytorch, and 3407 is all you need
load: 0                 # Whether load model and continue to train
train: 1                # To train the model or not
regenerate: 0           # Whether to regenerate intermediate files
dataset: 'ml-100k'      # the name of dataset

# Runner Settings:
runner:
  epoch: 300            # Number of epochs
  check_epoch: 1        # Check some tensors every check_epoch
  test_epoch: -1        # Print test results every test_epoch (-1 means no print)
  early_stop: 10        # The number of epochs when dev results drop continuously
  lr: !!float 1e-3      # Learning rate
  l2: !!float 0         # Weight decay in optimizer
  batch_size: 2056      # Batch size during training
  eval_batch_size: 2056 # Batch size during testing
  optimizer: 'Adam'     # optimizer: SGD, Adam, Adagrad, Adadelta
  num_workers: 5        # Number of processors when prepare batches in DataLoader
  pin_memory: 0         # pin_memory in DataLoader
  topk: '10,20'         # The number of items recommended to each user.
  metric: 'NDCG, HR'    # Evaluation metrics
  num_neg: 1            # sample one negative item while training
  test_all: 1           # Whether testing on all the items. Default is yes.

# Reader Settings
reader:
  path: '../data/'      # Input data dir
  dataset: 'ml-100k'    # Choose a dataset
  sep: '\t'             # sep of csv file
  buffer: 1             # Whether to buffer feed dicts for dev/test. Default is 1
