model:
    name: 'SGL'
    embedding_size: 64
    gcn_layers: 3
    reg_weight: !!float 1e-05
    type: 'ED'                      # (str) The type to generate views. Range in ['ED', 'ND', 'RW'].
    ssl_tau: 0.5                    # (float) The temperature in softmax.
    ssl_weight: 0.05                # (float) The hyperparameter to control the strengths of SSL.
    drop_ratio: 0.1                 # (float) The dropout ratio.
reader:
    name: 'BaseReader'
runner:
    name: 'BaseRunner'
    lr: !!float 1e-3
    l2: !!float 1e-8
    epoch: 400